// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	Request
	Response
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Response struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "model.Request")
	proto.RegisterType((*Response)(nil), "model.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ModelData service

type ModelDataClient interface {
	FindByID(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	FindQuery(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type modelDataClient struct {
	cc *grpc.ClientConn
}

func NewModelDataClient(cc *grpc.ClientConn) ModelDataClient {
	return &modelDataClient{cc}
}

func (c *modelDataClient) FindByID(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/model.ModelData/FindByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelDataClient) FindQuery(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/model.ModelData/FindQuery", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ModelData service

type ModelDataServer interface {
	FindByID(context.Context, *Request) (*Response, error)
	FindQuery(context.Context, *Request) (*Response, error)
}

func RegisterModelDataServer(s *grpc.Server, srv ModelDataServer) {
	s.RegisterService(&_ModelData_serviceDesc, srv)
}

func _ModelData_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDataServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.ModelData/FindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDataServer).FindByID(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelData_FindQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelDataServer).FindQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.ModelData/FindQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelDataServer).FindQuery(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModelData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.ModelData",
	HandlerType: (*ModelDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByID",
			Handler:    _ModelData_FindByID_Handler,
		},
		{
			MethodName: "FindQuery",
			Handler:    _ModelData_FindQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xe4, 0xb9, 0xd8, 0x83,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x0b, 0x4b, 0x53, 0x8b, 0x2a, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x25, 0x25, 0x2e, 0x8e, 0xa0, 0xd4, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xa8, 0x12,
	0x28, 0xcf, 0x28, 0x8b, 0x8b, 0xd3, 0x17, 0x64, 0x9a, 0x4b, 0x62, 0x49, 0xa2, 0x90, 0x2e, 0x17,
	0x87, 0x5b, 0x66, 0x5e, 0x8a, 0x53, 0xa5, 0xa7, 0x8b, 0x10, 0x9f, 0x1e, 0xc4, 0x4a, 0xa8, 0x15,
	0x52, 0xfc, 0x70, 0x3e, 0xc4, 0x44, 0x25, 0x06, 0x21, 0x3d, 0x2e, 0x4e, 0x90, 0xf2, 0x40, 0x90,
	0x65, 0x44, 0xa8, 0x4f, 0x62, 0x03, 0x3b, 0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x94, 0x6e,
	0xb1, 0x95, 0xcd, 0x00, 0x00, 0x00,
}
